name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1  # v2 is the correct version, not v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: docker compose version  # optional check to verify Docker Compose is available

      - name: Run tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run flake8 linter
        run: docker compose run --rm app sh -c "flake8"
